### ISSUE TITLE
gemspec typo in URL

### ISSUE THREAD

**Issue by tuxmea** [voxpupuli/puppet-lint-spaceship_operator_without_tag-check#19]
https://github.com/voxpupuli/puppet-lint-spaceship_operator_without_tag-check/blob/d2515b5c5c8caf7443120acdb71c280e0660ee45/puppet-lint-spaceship_operator_without_tag-check.gemspec#L4

correct url: https://github.com/voxpupuli/puppet-lint-spaceship_operator_without_tag-check

**Comment by ekohl** [comment]
Fixed in https://github.com/voxpupuli/puppet-lint-spaceship_operator_without_tag-check/commit/49c71dc14c5730a53293ac71bb35ad317c8981d5
