### ISSUE TITLE
Documented example Package <| virtual == true |> is not a valid search expression

### ISSUE THREAD

**Issue by killglance** [voxpupuli/puppet-lint-spaceship_operator_without_tag-check#4]
While cleaning up lint errors in our codebase, we followed quite blindly :) the example to use virtual == true to clear this lint check. Upon further testing it was confirmed that it is not a valid search expression and therefore no resources will be realized. 

Also checking the linked puppet issue, was never resolved: https://tickets.puppetlabs.com/browse/PUP-3825

to reproduce this using the following code and test:

## foo/manifests/init.pp
class foo {
  @user { 'foo':
    ensure => present,
  }
  User <| virtual == true |>

  @user { 'bar':
    ensure => present,
  }
  User <| title == 'bar' |>
}

## foo/spec/classes/foo_spec.rb
require 'spec_helper'

describe 'foo', :type => :class do
  it { should contain_user('foo').with_ensure('present') }
  it { should contain_user('bar').with_ensure('present') }
end

**Comment by killglance** [comment]
I'll open a PR with the documentation edits as well in a moment

**Comment by binford2k** [comment]
Fixed in #5
